= Projektauftrag
Moritz Eder, Abdulrahman Al Sabagh, Angerer Mona
1.0.0, 2021/22
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Projektbezeichnung

== Projektauftraggeber

== Projekthintergrund
Man findet heutzutage viele opensource Programme, die perfekte Funktionalitäten haben, doch die Programme sind so schlecht gecodet, dass man Stunden braucht, bis man irgendwie versteht wie die Programme funktionieren. Man kann diese Programme nicht erweitern oder sie für andere Programme anwenden.

== Projektendergebnis

== Projektziel
Ein Diagram für solche Programme generieren, um die Programme besser zu verstehen. Somit kann man das Programm besser verstehen und umcoden bzw. ändern damit jeder Mensch es und nachvollziehen kann. Der  Code kann dann erweitert werden bzw. in einem Projekt angewendet werden

== Projektbeschreibung

== Projektphasen/Meilensteine

== Projektstart

== Projektende

== Projektressourcen

== Projektrisiken

== Projektorganisation

== Abschluss des Projektauftrags



