= Inventory
Moritz Eder, Abdulrahman Al Sabagh, Angerer Mona
1.0.0, 2021/22
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Projektauftrag

=== Projektbezeichnung

Inventory

=== Projektauftraggeber

Thomas Stütz

=== Projekthintergrund

In jedem Gebäude gibt es Geräte, die regelmäßig gewartet bzw. ausgetauscht werden müssen. Es bedarf also einer Übersicht, auf der festgehalten wird, wann welches Gerät gewartet werden muss, oder welches das letzte Mal gewartet wurde, etc.

Ein einheitliches Programm auf dem man einen Überblick über alle Räume und Geräte eines Gebäudes hat, wird dies erheblich erleichtern.

=== Projektendergebnis

Ein funktionierendes Programm, dass Überblick über alle Räume und Geräte eines Gebäudes bietet und Wartungstermine zu den jeweiligen Geräten anzeigt.

=== Projektziel

Ziele für unser fertiges Projekt sind:

* benutzerfreundliche und übersichtliche Oberfläche
* Geräte können hinzugefügt und entfernt werden
* die Geräte werden chronologisch (welches Gerät muss als nächstes gewartet werden) dargestellt


=== Projektbeschreibung

Mithilfe unseres Projektes kann man einfach und übersichtlich alle Geräte eines Gebäudes verwalten. Die Geräte mit ihren dazugehörigen Wartungsterminen werden chronologisch angezeigt. Es können auch einfach Geräte hinzugefügt oder entfernt werden, falls notwendig.

=== Meilensteine

|=======================
|Meilenstein/Ergebnis|Datum
|Aufbau des Layouts + Funktionen|5.5.2022
|Tests|12.5.2022
|Protokolle und Passwort Funktion|  26.5.2022
|Performanz Optimierung|09.06.2022
|Projekt fertiggestellt|23.06.2022
|=======================

=== Projektressourcen

* IntelliJ IDEA
* Github
* Docker

=== Projektrisiken

* Falsche Daten beim Austauschen von Geräte
* Performanzprobleme

=== Projektorganisation

Projektleiter: Abdulrahman Al Sabagh: Zuständig für Model, Controller und Deployment

Projektteam +

- Moritz Eder: Zuständig für Unitests +
- Mona Angerer: Zuständig für View und Controller

=== ERD-Diagram

[plantuml,erd,png]
----
include::plantuml/erd.puml[]
----


////
== CLD (im Code)

[plantuml,code-cld,png]
----
include::plantuml/code-cld.puml[]
----
////


=== Anwendungsfalldiagramm

[plantuml,UseCase,png]
----
include::plantuml/ucd.puml[]
----

== Pflichtenheft

=== Ausgangssituation

In der HTL Leonding gibt es viele unterschiedliche technische Geräte, die oft erneuert und ausgetauscht werden.

=== Istzustand

Für die neu installierten Bildschirme in vielen Klassenräumen in der HTL Leonding gibt es derzeit keine einheitliche Anwendung mithilfe derer sie dargestellt und verwaltet werden können. Bei anderen Geräten ist das auch der Fall.

=== Aufgabenstellung

Für jeden neuen Bildschirm und andere Geräte wird man sich diese Fragen stellen können:

* Wie ist das Gerät identifizierbar?
* Von welcher Firma kommen es?
* Ist es austauschbar?
* Ist es kabellos?
* In welchem Stockwerk befindet sich es?
* In welchem Raum steht es?
* Zu welcher Kategorie ist es  zugewiesen?

=== Ziele

Ziel ist eine funktionierende, benutzerfreundliche Anwendung mit der einfach und unkompliziert alle Geräte eines Gebäudes verwaltet werden können und Geräte hinzugefügt, sowie entfernt werden können. Das Programm wird am Ende des Schuljahres fertiggestellt sein.

////
=== Mengengerüst
////

=== Rahmenbedingungen

* Dokumentation mit Asciidoc
* Anwendung wird mit JavaFx programmiert
* Anwendung ist bis Ende des Schuljahres fertiggestellt

=== GANTT-Diagramm

[plantuml, gantt chart, png]
-----
@startuml

[Aufbau Layout & Funktionen] lasts 21 days
[Prototype fertig] happens at [Aufbau Layout & Funktionen]'s end
[Tests] lasts 7 days
[Tests] starts at [Aufbau Layout & Funktionen]'s end
[Protokolle / Passwort Funktion] lasts 14 days
[Protokolle / Passwort Funktion] starts at [Tests]'s end
[Performanz Optimierung] lasts 14 days
[Performanz Optimierung] starts at [Protokolle / Passwort Funktion]'s end
[Projekt Fertigstellung] lasts 14 days
[Projekt Fertigstellung] starts at [Performanz Optimierung]'s end

@enduml
-----