= Feuerlöscherdistributionsverwaltungsprogramm
Moritz Eder, Abdulrahman Al Sabagh, Angerer Mona
1.0.0, 2021/22
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Projektbezeichnung

Feuerlöscherdistributionsverwaltungsprogramm

== Projektauftraggeber

Thomas Stütz

== Projekthintergrund

In jedem Gebäude gibt es Feuerlöscher, die regelmäßig gewartet bzw. ausgetauscht werden müssen. Es bedarf also einer Übersicht, auf der festgehalten wird, wann welcher Feuerlöscher gewartet werden muss, dass letzte Mal gewartet wurde, etc.

Ein einheitliches Programm auf dem man einen Überblick über alle Räume und Feuerlöscher eines Gebäudes hat, wird dies erheblich erleichtern.

== Projektendergebnis

Ein funktionierendes Programm, dass Überblick über alle Räume und Feuerlöscher eines Gebäudes bietet und Wartungstermine zu den jeweiligen Feuerlöschern anzeigt.

== Projektziel

Ziele für unser fertiges Projekt sind:

* benutzerfreundliche und übersichtliche Oberfläche
* Feuerlöscher können hinzugefügt und entfernt werden
* die Feuerlöscher werden chronologisch (welcher Feuerlöscher muss als nächstes gewartet werden) dargestellt


== Projektbeschreibung

Mithilfe unseres Projektes kann man einfach und übersichtlich alle Feuerlöscher eines Gebäudes verwalten. Die Feuerlöscher mit ihren dazugehörigen Wartungsterminen werden chronologisch angezeigt. Es können auch einfach Feuerlöscher hinzugefügt oder entfernt werden, falls notwendig.

== Meilensteine

|=======================
|Meilenstein/Ergebnis|Datum
|Aufbau des Layouts + Funktionen|5.5.2022
|Tests|12.5.2022
|Benachrichtigungsfunktion hinzufügen|  26.5.2022
|Performanz Optimierung|09.06.2022
|Projekt fertiggestellt|23.06.2022
|=======================

== Projektressourcen

* IntelliJ IDEA
* Github
* Docker

== Projektrisiken

* Falsche Daten beim Austauschen von Feuerlöschern
* Performanzprobleme

== Projektorganisation

Projektleiter: Abdulrahman Al Sabagh: Zuständig für Model, Controller und Deployment

Projektteam +

- Moritz Eder: Zuständig für Unitests +
- Mona Angerer: Zuständig für View und Controller

== ERD-Diagram

[plantuml,erd,png]
----
include::plantuml/erd.puml[]
----


////
== CLD (im Code)

[plantuml,code-cld,png]
----
include::plantuml/code-cld.puml[]
----
////


== Anwendungsfalldiagramm

[plantuml,UseCase,png]
----
include::plantuml/ucd.puml[]
----


