@startuml
start

'Nur für Abudi'
:erstelle einen Timer, der die Millisekunden zählt;
if (Schüler tippt) then
:Timer zählt weiter;
    else (Timer stoppen)
    endif

    if (Timer %5 == 0)  then
    :Screenshot aufnehmen und speichern;
    stop
    else
  :zähle weiter;
  stop
@enduml