@startuml
'https://plantuml.com/class-diagram
left to right direction
class Firma {
- firmenNr :int
- name:String
||
}
class Raum {
 - raumNr:int
 - stockwerk:int
 -  feuerloescherNr: int
 ||
}
class Feuerloescher {
 - feuerloescherNr:int
 - firmenNr: int
 - austauschbar: boolean
||
}
class Termin {
    - terminNr: int
    - datum: Date
||
}

class Wartung {
    - wartungsNr: int
   - terminNr : int
   - feuerloescherNr: int
   ||
}

class Benachrichtigung {
  - id:int
  - nachricht: String
  - typ: String
  ||
}

Raum "1" <-- "*" Feuerloescher

Feuerloescher "*" --  "*" Termin

(Feuerloescher,Termin) .. Wartung

Firma "1" <-- "*" Feuerloescher
note as nachricht

Typen von Nachrichten:

- Warnung
- Erinnerung
- Aktivität  z.B.: (Feuerlöscher xy wurde hinzugefügt)
end note


@enduml